#!/bin/bash
set -e

CURRENT_DIR=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

OSX_PKEY_INSTALLER=${CURRENT_DIR}/devid_installer/devid_installer.p12
OSX_PKEY_APPLICATION=${CURRENT_DIR}/devid_application/devid_application.p12
OSX_PKEY_INSTALLER_PASS=4gCNlhOW13gK
OSX_PKEY_APPLICATION_PASS=4gCNlhOW13gK

#appstore connect key is a jsonfile generated by rcodesign tool
OSX_APPSTORE_CONNECT_KEY=${CURRENT_DIR}/appstore_connect/api_key.json