#!/bin/bash

APP_NAME=Cellframe-Dashboard
DAP_PREFIX=/Users/$USER/Applications/Cellframe.app/Contents/Resources
SERVICE=com.demlabs."$APP_NAME"Service
NODE=com.demlabs.cellframe-node

set -x
sudo xattr -rd com.apple.quarantine /Applications/"$APP_NAME".app
sudo killall -HUP mDNSResponder

EXEC_PREFIX=/Applications/$APP_NAME.app/Contents/Resources

#log dirs
mkdir -p /var/log/cellframe-dashboard/ || true
chmod -R 777 /var/log/cellframe-dashboard/ || true

mkdir -p $DAP_PREFIX
mkdir -p $DAP_PREFIX/etc
mkdir -p $DAP_PREFIX/share 

sudo cp -rf /Applications/$APP_NAME.app/Contents/Resources/etc/* $DAP_PREFIX/etc
sudo cp -rf /Applications/$APP_NAME.app/Contents/Resources/share/* $DAP_PREFIX/share
sudo mkdir -p $DAP_PREFIX/var/run/ || true

for filename in $(find $DAP_PREFIX | grep -v bugreport); do
    if [ -d $filename ]; then
        chmod 0775 $filename || true
    else
        chmod 0664 $filename || true
    fi
done

wd=$(pwd)
cd $EXEC_PREFIX/../MacOS

for filename in $(ls . | grep -v '.'); do
    if [ -L $filename ] && [ ! -e $filename ]; then
        strip -u -r $filename
    fi
done

sudo chmod +x $EXEC_PREFIX/create_configs.sh
sudo chmod +x $EXEC_PREFIX/create_configs_from_tpl.sh

$EXEC_PREFIX/create_configs.sh /Applications/Cellframe-Dashboard.app/

#mkdir -p /Users/$USER/Library/LaunchAgents
launchctl stop $SERVICE 
sudo  launchctl unload -w /Library/LaunchDaemons/$SERVICE.plist

launchctl stop $NODE
sudo  launchctl unload -w /Library/LaunchDaemons/$NODE.plist

sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$SERVICE.plist /Library/LaunchDaemons/$SERVICE.plist
sudo ln -sf /Applications/"$APP_NAME".app/Contents/Resources/$NODE.plist /Library/LaunchDaemons/$NODE.plist
sudo launchctl load -w /Library/LaunchDaemons/$NODE.plist
sudo launchctl load -w /Library/LaunchDaemons/$SERVICE.plist

#  rm -r $DAP_PREFIX/var/lib/global_db/ || true
#  rm -r $DAP_PREFIX/var/lib/network/ || true

sudo  launchctl start $NODE
sudo  launchctl start $SERVICE

sudo rm $EXEC_PREFIX/*.sh
sudo rm /Applications/$APP_NAME.plist
sudo rm /Applications/Cellframe.app

cp /Applications/$APP_NAME.app/Contents/Resources/cellframe-uninstaller /Applications
Rez -append /Applications/$APP_NAME.app/Contents/Resources/uninstall_icon.rsrc -o /Applications/cellframe-uninstaller
SetFile -a C /Applications/cellframe-uninstaller

echo "node agent: $(launchctl list | grep cell)" > /tmp/cellframe-dashboard_install_logs.txt
echo "service agent: $(launchctl list | grep cell)" > /tmp/cellframe-dashboard_install_logs.txt

cd $wd

