#before_build:
    

stages:
    - prepare
    - build
    - test
    - deploy
    - update 

variables:
    GIT_SUBMODULE_STRATEGY: normal

cellframe-dashboard_update:
    stage: update
    rules:
    - if: $UPDATE != "true"
  #    ref: master
    tags:
     - cellframe-dashboard
  # only:
  #   - master
    script: ~/scripts/update_CellFrameDashboard.sh

cellframe-dashboard_linux:
    stage: build
    rules:
    - if: $UPDATE == "true"
    tags:
     - cellframe-dashboard
    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard linux


cellframe-dashboard_windows:
   stage: build
   rules:
    - if: $UPDATE == "true"
   tags:
    - cellframe-dashboard
   script: ~/production-docker/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard windows

# Test
# run unit-tests

# Deploy
# cp to builds folder
