stages:
    - prepare
    - build
    - test

variables:
    GIT_SUBMODULE_STRATEGY: normal

kelvin-node-schedule:
    stage: build
    tags:
    - kelvin-dashboard
    only:
    - schedules
    script: ~/production/integration/gitlab-CI/build_all_handler.sh kelvin-dashboard
