#before_build:
    

stages:
    - prepare
    - build
    - test
    - deploy

variables:
    GIT_SUBMODULE_STRATEGY: normal

# Prepare
#
#

# cellframe-dashboard-test:
#     stage: build
#     tags:
#      - cellframe-dashboard
#     except:
#      - merge_request
#      - develop
#      - master
#      - /^pubtest.*$/
#      - /^release.*$/
#     script: ~/production/integration/gitlab-CI/build_test_handler.sh cellframe-dashboard

# cellframe-dashboard-merge-request-windows:
#    stage: build
#    tags:
#     - cellframe-dashboard
#    only: [merge_requests]
#    except:
#      variables:
#        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
#        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "/^release.*$/"
#    script: ~/production-docker/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard windows

# cellframe-dashboard-merge-request-linux:
#     stage: build
#     tags:
#      - cellframe-dashboard
#     only: [merge_requests]
#     except:
#       variables:
#         - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
#         - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "/^release.*$/"
#     script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard linux

#cellframe-dashboard-merge-request-mac:
#    stage: build
#    tags:
#     - cellframe-dashboard
#    only: [merge_requests]
#    except:
#      variables:
#        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard mac

#cellframe-dashboard-merge-request-android:
#    stage: build
#    tags:
#     - cellframe-dashboard
#    only: [merge_requests]
#    except:
#      variables:
#        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard android

# cellframe-dashboard-schedule:
#     stage: build
#     tags: 
#      - cellframe-dashboard
#     only:
#      - schedules
#     script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard

cellframe-dashboard_linux:
    stage: build
    tags:
     - cellframe-dashboard
    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard linux

#cellframe-dashboard_mac:
#    stage: build
#    tags:
#     - cellframe-dashboard
#    only:
#     - master
#     - /^release.*$/
#     - /^pubtest.*$/
#     - develop
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard mac

#cellframe-dashboard_android:
#    stage: build
#    tags:
#     - cellframe-dashboard
#    only:
#     - master
#     - /^release.*$/
#     - /^pubtest.*$/
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard android

cellframe-dashboard_windows:
   stage: build
   tags:
    - cellframe-dashboard
   script: ~/production-docker/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard windows

# Test
# run unit-tests

# Deploy
# cp to builds folder
