#before_build:
    

stages:
    - prepare
    - build
    - test
    - deploy

variables:
    GIT_SUBMODULE_STRATEGY: normal

# Prepare
#
#

dapchain-client-test:
    stage: build
    tags:
     - dapchain-client
    except:
     - merge_request
     - develop
     - master
     - /^pubtest.*$/
     - /^release.*$/
    script: ~/production/integration/gitlab-CI/build_test_handler.sh cellframe-dashboard

#dapchain-client-merge-request-windows:
#    stage: build
#    tags:
#     - dapchain-client
#    only: [merge_requests]
#    except:
#      variables:
#        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard windows

dapchain-client-merge-request-linux:
    stage: build
    tags:
     - dapchain-client
    only: [merge_requests]
    except:
      variables:
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "/^release.*$/"
    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard linux

#dapchain-client-merge-request-mac:
#    stage: build
#    tags:
#     - dapchain-client
#    only: [merge_requests]
#    except:
#      variables:
#        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard mac

#dapchain-client-merge-request-android:
#    stage: build
#    tags:
#     - dapchain-client
#    only: [merge_requests]
#    except:
#      variables:
#        - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "master"
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard android

dapchain-client-schedule:
    stage: build
    tags: 
     - dapchain-client
    only:
     - schedules
    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard

dapchain-client_linux:
    stage: build
    tags:
     - dapchain-client
    only:
     - master
     - /^release.*$/
     - /^pubtest.*$/
    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard linux

#dapchain-client_mac:
#    stage: build
#    tags:
#     - dapchain-client
#    only:
#     - master
#     - /^release.*$/
#     - /^pubtest.*$/
#     - develop
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard mac

#dapchain-client_android:
#    stage: build
#    tags:
#     - dapchain-client
#    only:
#     - master
#     - /^release.*$/
#     - /^pubtest.*$/
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard android

#dapchain-client_windows:
#    stage: build
#    tags:
#     - dapchain-client
#    only:
#     - /^pubtest.*$/
#     - /^release.*$/
#    except:
#     - master
#    script: ~/production/integration/gitlab-CI/build_all_handler.sh cellframe-dashboard windows

# Test
# run unit-tests

# Deploy
# cp to builds folder
