variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - deploy
    - publish
.ci-polygon:
  tags:
     - ci-polygon
  
.build:  
  extends: .ci-polygon
  stage: build
  timeout: 3 hours 30 minutes
  dependencies: []
  artifacts:
    paths:
      - build_*/*.deb

.deploy:
  extends: .ci-polygon
  image: demlabs/amd64/debian-buster:linuxbuilder
  stage: deploy
  before_script: /opt/buildtools/prepare_environment.sh 

.publish:
  extends: .deploy
  stage: publish
  allow_failure: true

macos-amd64:
    extends: .build
    image: demlabs/amd64/debian-bullseye:osxbuilderssl
    before_script: /opt/buildtools/prepare_environment.sh amd64-osx
    script:
      - ./prod_build/build.sh --target osx release
      - ./prod_build/pack.sh --target osx release --sign /opt/buildtools/sign/macos/demlabs.sh
    artifacts:
      paths:
        - build_*/*.pkg

linux-amd64-debian-buster:
    extends: .build
    image: demlabs/amd64/debian-buster:linuxbuilder
    before_script: /opt/buildtools/prepare_environment.sh amd64-linux
    script: 
      - ./prod_build/build.sh --target linux release
      - ./prod_build/pack.sh --target linux release
      - anybadge -l "master version" -v "$(source version.mk; echo "$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH")" -f version-badge.svg -c blue
      - /opt/buildtools/deploy_files.sh pub_cellframe linux/cellframe-dashboard/$CI_COMMIT_REF_NAME/ ./version-badge.svg || true
      
<<<<<<< HEAD
linux-rwd-amd64-debian-buster:
=======
linux-debug-amd64-debian-buster:
>>>>>>> 91df5d336742da0a454a1833dd6b8e91bf8349a3
    extends: .build
    image: demlabs/amd64/debian-buster:linuxbuilder
    before_script: /opt/buildtools/prepare_environment.sh amd64-linux
    script: 
<<<<<<< HEAD
      - ./prod_build/build.sh --target linux rwd
      - ./prod_build/pack.sh --target linux rwd
=======
      - ./prod_build/build.sh --target linux debug
      - ./prod_build/pack.sh --target linux debug
>>>>>>> 91df5d336742da0a454a1833dd6b8e91bf8349a3
      

windows-amd64:
    extends: .build
    image: demlabs/amd64/debian-bullseye:windowsbuilder
    before_script: /opt/buildtools/prepare_environment.sh amd64-linux
    script:
      - ./prod_build/build.sh --target windows release
      - ./prod_build/pack.sh --target windows release
    artifacts:
      paths:
        - build_*/*.exe


deploy-linux:
  extends: .deploy
  needs: 
    - linux-amd64-debian-buster
<<<<<<< HEAD
    - linux-rwd-amd64-debian-buster
=======
    - linux-debug-amd64-debian-buster
>>>>>>> 91df5d336742da0a454a1833dd6b8e91bf8349a3
 
  script: 
    - /opt/buildtools/deploy_files.sh pub_cellframe linux/cellframe-dashboard/$CI_COMMIT_REF_NAME/ build_*/*.deb 
    
    
deploy-macos:
  extends: .deploy
  needs: 
    - macos-amd64
   
  script: 
    - /opt/buildtools/deploy_files.sh pub_cellframe macos/cellframe-dashboard/$CI_COMMIT_REF_NAME/ build_*/*.pkg
    
deploy-windows:
  extends: .deploy
  needs: 
    - windows-amd64
   
  script: 
    - /opt/buildtools/deploy_files.sh pub_cellframe windows/cellframe-dashboard/$CI_COMMIT_REF_NAME/ build_*/*.exe 
  
  #=================PUBLISH KELVPN===================
publish-linux:
  extends: .publish
  needs: 
    - linux-amd64-debian-buster 
    - deploy-linux
  script: 
    - /opt/buildtools/deploy_files.sh pub_cellframe linux/cellframe-dashboard/$CI_COMMIT_REF_NAME/  build_*/*.deb --redirect-from linux/cellframe-dashboard/$CI_COMMIT_REF_NAME/latest --just-redirect
    - anybadge -l "pub linux" -v "$(source version.mk; echo "$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH")" -f version-badge.svg -c green
    - /opt/buildtools/deploy_files.sh pub_cellframe linux/cellframe-dashboard/$CI_COMMIT_REF_NAME/latest ./version-badge.svg
    
publish-windows:
  extends: .publish
  needs: 
    - windows-amd64 
    - deploy-windows
  script: 
    - /opt/buildtools/deploy_files.sh pub_cellframe windows/cellframe-dashboard/$CI_COMMIT_REF_NAME/  build_*/*.exe  --redirect-from windows/cellframe-dashboard/$CI_COMMIT_REF_NAME/latest --just-redirect
    - anybadge -l "pub windows" -v "$(source version.mk; echo "$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH")" -f version-badge.svg -c green
    - /opt/buildtools/deploy_files.sh pub_cellframe windows/cellframe-dashboard/$CI_COMMIT_REF_NAME/latest ./version-badge.svg    

publish-macos:
  extends: .publish
  needs: 
    - macos-amd64
    - deploy-macos
  script: 
    - /opt/buildtools/deploy_files.sh pub_cellframe macos/cellframe-dashboard/$CI_COMMIT_REF_NAME/  build_*/*.pkg --redirect-from macos/cellframe-dashboard/$CI_COMMIT_REF_NAME/latest --just-redirect
    - anybadge -l "pub macos" -v "$(source version.mk; echo "$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH")" -f version-badge.svg -c green
    - /opt/buildtools/deploy_files.sh pub_cellframe macos/cellframe-dashboard/$CI_COMMIT_REF_NAME/latest ./version-badge.svg    
