
build_dependencies:
  deb:
    - 'build-essential'
    - 'libmagic-dev'
    - 'libsqlite3-dev'
    - 'libjson-c-dev' 
    - 'libffi-dev'
    - 'file'
    - 'osslsigncode'
    

deploy_dependencies:
  deb:
    - 'ssh'
    