HEADERS += $$PWD/TxExplorer/DapModuleTxExplorer.h \
    $$PWD/DapModulesController.h \
    $$PWD/Dex/DapModuleDexLightPanel.h \
    $$PWD/Dex/DapRegularTokenType.h \
    $$PWD/Dex/StockDataWorker/ChartTypes.h \
    $$PWD/Dex/StockDataWorker/DapCommonDexMethods.h \
    $$PWD/Dex/StockDataWorker/MainInfoChart.h \
    $$PWD/Dex/StockDataWorker/CreateCandleChart.h \
    $$PWD/Dex/StockDataWorker/CreatingSheduleController.h \
    $$PWD/Diagnostics/DiagtoolConnectCotroller.h \
    $$PWD/Logs/DapModuleLogs.h \
    $$PWD/Logs/DapLogsReader.h \
    $$PWD/Logs/logmodel.h \
    $$PWD/Logs/logreader.h \
    $$PWD/Logs/loginfo.h \
    $$PWD/Console/DapModuleConsole.h \
    $$PWD/Console/consoleitem.h \
    $$PWD/DapAbstractModule.h \
    $$PWD/Certificates/DapModuleCertificates.h \
    $$PWD/MasterNode/DapMasterNodeKeys.h \
    $$PWD/MasterNode/MasterNodeCommand/DapAbstractMasterNodeCommand.h \
    $$PWD/MasterNode/MasterNodeCommand/DapNodeDelStage.h \
    $$PWD/MasterNode/MasterNodeCommand/DapSrvStakeInvalidateStage.h \
    $$PWD/MasterNode/MasterNodeCommand/DapStakeDelegate.h \
    $$PWD/MasterNode/MasterNodeCommand/DapUpdateConfigStage.h \
    $$PWD/MasterNode/MasterNodeCommand/DapWaitingPermission.h \
    $$PWD/Networks/DapModuleNetworks.h \
    $$PWD/Settings/DapModuleSettings.h \
    $$PWD/Dex/DapModuleDex.h \
    $$PWD/Dex/StockDataWorker/OrderBookWorker.h \
    $$PWD/Dex/StockDataWorker/CandleChartWorker.h \
    $$PWD/Dex/StockDataWorker/StockDataWorker.h \
    $$PWD/Dex/StockDataWorker/TokenPairsWorker.h \
    $$PWD/Dex/StockDataWorker/TokenPairInfo.h \
    $$PWD/Diagnostics/AbstractDiagnostic.h \
    $$PWD/Diagnostics/DapModuleDiagnostics.h \
    $$PWD/Orders/DapModuleOrders.h \
    $$PWD/Tokens/DapModuleTokens.h \
    $$PWD/TxExplorer/DapModuleTxExplorerAddition.h \
    $$PWD/Wallet/DapModuleWalletAddition.h \
    $$PWD/dApps/DapDappsNetworkManager.h \
    $$PWD/dApps/DapModuledApps.h \
    $$PWD/Wallet/WalletRestore/wallethashmanager.h \
    $$PWD/Wallet/WalletRestore/randomwords.h \
    $$PWD/Wallet/WalletRestore/randomfile.h \
    $$PWD/Wallet/DapModuleWallet.h \
    $$PWD/MasterNode/DapModuleMasterNode.h 

 SOURCES += $$PWD/TxExplorer/DapModuleTxExplorer.cpp \
    $$PWD/Dex/DapModuleDexLightPanel.cpp \
    $$PWD/Dex/DapRegularTokenType.cpp \
    $$PWD/Dex/StockDataWorker/CreateCandleChart.cpp \
    $$PWD/Dex/StockDataWorker/DapCommonDexMethods.cpp \
    $$PWD/Dex/StockDataWorker/MainInfoChart.cpp \
    $$PWD/Dex/StockDataWorker/CreatingSheduleController.cpp \
    $$PWD/Diagnostics/DiagtoolConnectCotroller.cpp \
    $$PWD/Logs/logreader.cpp \
    $$PWD/Logs/DapModuleLogs.cpp \
    $$PWD/Logs/logmodel.cpp \
    $$PWD/Logs/DapLogsReader.cpp \
    $$PWD/Console/DapModuleConsole.cpp \
    $$PWD/Certificates/DapModuleCertificates.cpp \
    $$PWD/MasterNode/DapMasterNodeKeys.cpp \
    $$PWD/MasterNode/MasterNodeCommand/DapAbstractMasterNodeCommand.cpp \
    $$PWD/MasterNode/MasterNodeCommand/DapNodeDelStage.cpp \
    $$PWD/MasterNode/MasterNodeCommand/DapSrvStakeInvalidateStage.cpp \
    $$PWD/MasterNode/MasterNodeCommand/DapStakeDelegate.cpp \
    $$PWD/MasterNode/MasterNodeCommand/DapUpdateConfigStage.cpp \
    $$PWD/MasterNode/MasterNodeCommand/DapWaitingPermission.cpp \
    $$PWD/Networks/DapModuleNetworks.cpp \
    $$PWD/Settings/DapModuleSettings.cpp \
    $$PWD/Dex/DapModuleDex.cpp \
    $$PWD/Dex/StockDataWorker/StockDataWorker.cpp \
    $$PWD/Dex/StockDataWorker/CandleChartWorker.cpp \
    $$PWD/Dex/StockDataWorker/OrderBookWorker.cpp \
    $$PWD/Dex/StockDataWorker/TokenPairsWorker.cpp \
    $$PWD/DapModulesController.cpp \
    $$PWD/Diagnostics/DapModuleDiagnostics.cpp \
    $$PWD/Orders/DapModuleOrders.cpp \
    $$PWD/Diagnostics/AbstractDiagnostic.cpp \
    $$PWD/Tokens/DapModuleTokens.cpp \
    $$PWD/TxExplorer/DapModuleTxExplorerAddition.cpp \
    $$PWD/Wallet/BalanceFuncHelper.cpp \
    $$PWD/Wallet/DapModuleWalletAddition.cpp \
    $$PWD/dApps/DapDappsHelpFunctions.cpp \
    $$PWD/dApps/DapDappsNetworkManager.cpp \
    $$PWD/dApps/DapModuledApps.cpp \
    $$PWD/DapAbstractModule.cpp \
    $$PWD/Wallet/WalletRestore/wallethashmanager.cpp \
    $$PWD/Wallet/WalletRestore/randomwords.cpp \
    $$PWD/Wallet/WalletRestore/randomfile.cpp \
    $$PWD/Wallet/DapModuleWallet.cpp \
    $$PWD/MasterNode/DapModuleMasterNode.cpp 
