-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglP98jAyohyQl/TT1
sFEZanmj4HB7jVzduaJ5ncxSGW2gCgYIKoZIzj0DAQehRANCAAQO48rRTTkQ7NcU
2rZchkOd4UhUauUI33zMX+OwmuIbfmxjjnww4n3fjaxdPNAZPoM+dzHtVjEjWGqW
IayfxBSS
-----END PRIVATE KEY-----