#!/bin/bash -

. /usr/share/debconf/confmodule

DAP_CHAINS_NAME="cellframe"
DAP_DASHBOARD_NAME="$DAP_CHAINS_NAME-dashboard"
DAP_DASHBOARD_PREFIX="/opt/$DAP_DASHBOARD_NAME"

APP_NAME=Cellframe-Dashboard

case "$1" in
    configure)

    ln -sf /opt/cellframe-dashboard/share/init.d/cellframe-dashboard.service /etc/systemd/user/cellframe-dashboard.service
    systemctl --system enable /opt/cellframe-dashboard/share/init.d/cellframe-dashboard.service
    chmod +x /opt/cellframe-dashboard/bin/*
    ln -sf /opt/cellframe-dashboard/bin/$APP_NAME /usr/local/bin/$APP_NAME
    
    if ! [ -f "/usr/lib/x86_64-linux-gnu/libxcb-util.so.0" ]; then
   	 	ln /usr/lib/x86_64-linux-gnu/libxcb-util.so.1 /usr/lib/x86_64-linux-gnu/libxcb-util.so.0
	fi
    
    cp -f /opt/cellframe-dashboard/share/CellFrameDashboard.desktop /usr/share/applications/CellFrameDashboard.desktop
	cp -f /opt/cellframe-dashboard/share/CellframeDashboard.png	/usr/share/pixmaps/CellframeDashboard.png
    update-menus

#    echo "For start CellFrame Dashboard Service - run 'systemctl start cellframe-dashboard'"
;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 2
    ;;
esac

# rm -r /opt/cellframe-node/var/lib/network/ || true
# rm -r /opt/cellframe-node/var/lib/global_db/ || true
chmod 777 /opt/cellframe-node/var/lib/ca #for import CA by using dashboard
mkdir /var/log/cellframe-dashboard/ || true
chmod -R a+rw /var/log/cellframe-dashboard/

service cellframe-dashboard start || true



