#!/bin/bash -

. /usr/share/debconf/confmodule

DAP_CHAINS_NAME="cellframe"
DAP_DASHBOARD_NAME="$DAP_CHAINS_NAME-dashboard"
DAP_DASHBOARD_PREFIX="/opt/$DAP_DASHBOARD_NAME"

APP_NAME=Cellframe-Dashboard

case "$1" in
    configure)

    ln -sf /opt/cellframe-dashboard/share/init.d/cellframe-dashboard.service /etc/systemd/user/cellframe-dashboard.service
    systemctl --system enable /opt/cellframe-dashboard/share/init.d/cellframe-dashboard.service
    chmod +x /opt/cellframe-dashboard/bin/*
    ln -sf /opt/cellframe-dashboard/bin/$APP_NAME /usr/local/bin/$APP_NAME
    
    cp -f /opt/cellframe-dashboard/share/CellFrameDashboard.desktop /usr/share/applications/CellFrameDashboard.desktop
	cp -f /opt/cellframe-dashboard/share/CellFrameDashboard.ico	/usr/share/pixmaps/CellFrameDashboard.ico
    update-menus
    service cellframe-dashboard restart
#    echo "For start CellFrame Dashboard Service - run 'systemctl start cellframe-dashboard'"
;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 2
    ;;
esac



