#!/bin/bash

case "$1" in
    purge|remove|abort-upgrade|failed-upgrade|upgrade)
    [ -f /usr/local/bin/Cellframe-Wallet ] && rm /usr/local/bin/Cellframe-Wallet
    [ -f /usr/share/applications/CellFrameWallet.desktop ] && rm /usr/share/applications/CellFrameWallet.desktop
    [ -f /usr/share/pixmaps/CellFrameWallet.ico ] && rm /usr/share/pixmaps/CellFrameWallet.ico
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

